'use client'
import {useEffect,useMemo,useState} from 'react'
import {Search,RefreshCw,ExternalLink,Users,Eye,Heart,ThumbsUp,ThumbsDown,CalendarDays,Server,BarChart3,Activity,Star} from 'lucide-react'
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,BarChart,Bar} from 'recharts'

type Game=any
const fmt=(n:number|null|undefined)=>n==null?'—':Intl.NumberFormat('fr-FR',{notation:'compact',maximumFractionDigits:2}).format(n)
const date=(x:string|null)=>x?new Date(x).toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'}):'—'

export default function Home(){
 const [q,setQ]=useState(''); const [results,setResults]=useState<Game[]>([]); const [game,setGame]=useState<Game|null>(null); const [loading,setLoading]=useState(false); const [history,setHistory]=useState<any[]>([]); const [tab,setTab]=useState('overview'); const [focused,setFocused]=useState(false)
 useEffect(()=>{const h=localStorage.getItem('rbx-history');if(h)setHistory(JSON.parse(h))},[])
 useEffect(()=>{if(!game)return;const point={t:new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),players:game.playing,visits:game.visits,favorites:game.favorites};setHistory(h=>{const next=[...h.filter(x=>Date.now()-x.ms<86400000),{...point,ms:Date.now(),id:game.id}].slice(-60);localStorage.setItem('rbx-history',JSON.stringify(next));return next})},[game])
 async function search(){if(!q.trim())return;setLoading(true);try{const r=await fetch(`/api/roblox?action=search&q=${encodeURIComponent(q)}`);const d=await r.json();setResults(d.results||[]);if((d.results||[]).length===1)load(d.results[0].id)}finally{setLoading(false)}}
 async function load(id:string){setLoading(true);setResults([]);try{const r=await fetch(`/api/roblox?action=game&q=${id}`);const d=await r.json();setGame(d);setTab('overview')}finally{setLoading(false)}}
 const hist=useMemo(()=>history.filter(x=>x.id===game?.id).map(x=>({time:x.t,players:x.players,visits:x.visits})),[history,game])
 return <main className="shell">
  <header className="top"><div className="brand">RBX<span>Analytics</span></div><div className="search" style={{position:'relative'}}><input value={q} onChange={e=>setQ(e.target.value)} onFocus={()=>setFocused(true)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Rechercher un jeu Roblox ou coller son ID / URL…"/><button className="btn primary" onClick={search}><Search size={17}/></button>{focused&&results.length>0&&<div className="results">{results.map((r:any)=><div className="result" key={r.id} onClick={()=>load(r.id)}><img src={`https://tr.rbxcdn.com/${r.id}/420/420/Image/Png`}/><div><b>{r.name}</b><div className="sub">{fmt(r.playing)} joueurs · {fmt(r.visits)} visites</div></div></div>)}</div>}</div><button className="btn" onClick={()=>game&&load(game.id)} disabled={!game||loading}><RefreshCw size={17}/></button></header>
  {!game?<div className="empty"><BarChart3 size={48}/><h1>Analyse n'importe quelle expérience Roblox.</h1><p>Joueurs en ligne, visites, favoris, votes, rating, activité, historique local et bien plus.</p></div>:<>
   <section className="hero"><img src={game.icon||`https://tr.rbxcdn.com/${game.id}/420/420/Image/Png`} /><div style={{flex:1}}><h1>{game.name}</h1><div className="sub">Universe ID {game.id} · Place {game.placeId||'—'} · Créé le {date(game.created)} · Mis à jour le {date(game.updated)}</div><p className="sub" style={{maxWidth:900}}>{game.description||'Aucune description disponible.'}</p></div><a className="btn" href={`https://www.roblox.com/games/${game.placeId||game.id}`} target="_blank"><ExternalLink size={16}/> Roblox</a></section>
   <nav className="tabs">{['overview','engagement','ratings','technical','raw'].map(x=><button key={x} className={`tab ${tab===x?'active':''}`} onClick={()=>setTab(x)}>{({overview:'Vue générale',engagement:'Engagement',ratings:'Votes & rating',technical:'Technique',raw:'Données brutes'} as any)[x]}</button>)}</nav>
   {tab==='overview'&&<>
    <section className="grid">{[[Users,'Joueurs',game.playing], [Eye,'Visites',game.visits],[Heart,'Favoris',game.favorites],[Star,'Rating',game.rating==null?'—':`${game.rating.toFixed(2)}%`]].map(([I,l,v]:any)=><div className="card" key={l}><div className="label"><I size={14}/> {l}</div><div className="value">{typeof v==='number'?fmt(v):v}</div><div className="delta">Live · actualisé à l'ouverture</div></div>)}</section>
    <section className="section"><div className="sectionTitle"><h2>Activité observée</h2><span className="sub">Historique local des mesures de ce navigateur</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={hist.length?hist:[{time:'—',players:0}]}><CartesianGrid strokeDasharray="3 3" stroke="#202b38"/><XAxis dataKey="time" stroke="#778397"/><YAxis stroke="#778397"/><Tooltip contentStyle={{background:'#111823',border:'1px solid #263343',borderRadius:8}}/><Area type="monotone" dataKey="players" stroke="#72ff9b" fill="#72ff9b" fillOpacity={.12} name="Joueurs"/></AreaChart></ResponsiveContainer></div></section>
    <section className="two section"><div className="card"><div className="sectionTitle"><h2>Informations du jeu</h2></div>{[['Créateur',game.creator?.name||game.creator?.id||'—'],['Genre',game.genre||'—'],['Taille max serveur',game.maxPlayers],['Prix',game.price==null?'Gratuit':`${game.price} Robux`],['Serveurs privés',game.privateServerPrice==null?'—':`${game.privateServerPrice} Robux`],['Avatar',game.avatarType||'—']].map(([a,b])=><div className="row" key={String(a)}><span className="muted">{a}</span><b>{typeof b==='number'?fmt(b):b}</b></div>)}</div><div className="card"><div className="sectionTitle"><h2>Ratio d'activité</h2></div><div className="stats"><div><div className="label">Joueurs / visites</div><div className="value">{game.visits?((game.playing/game.visits)*100).toFixed(4)+'%':'—'}</div></div><div><div className="label">Favoris / visites</div><div className="value">{game.visits?((game.favorites/game.visits)*100).toFixed(3)+'%':'—'}</div></div><div><div className="label">Like ratio</div><div className="value">{game.rating==null?'—':game.rating.toFixed(2)+'%'}</div></div><div><div className="label">Visites / joueur live</div><div className="value">{game.playing?fmt(game.visits/game.playing):'—'}</div></div></div></div></section>
   </>}
   {tab==='engagement'&&<section className="grid">{[['CCU',game.playing],['Total visits',game.visits],['Favorites',game.favorites],['Visits / CCU',game.playing?game.visits/game.playing:null],['Favorites / visit',game.visits?game.favorites/game.visits*100:null],['Server capacity',game.maxPlayers],['Estimated active servers',game.maxPlayers?Math.ceil(game.playing/game.maxPlayers):null],['Update age',game.updated?Math.round((Date.now()-new Date(game.updated).getTime())/86400000)+' j':null]].map(([a,b])=><div className="card" key={String(a)}><div className="label">{a}</div><div className="value">{typeof b==='number'?fmt(b):b==null?'—':b}</div></div>)}</section>}
   {tab==='ratings'&&<section className="two"><div className="card"><h2>Votes</h2><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{name:'Likes',value:game.likes||0},{name:'Dislikes',value:game.dislikes||0}]}><CartesianGrid strokeDasharray="3 3" stroke="#202b38"/><XAxis dataKey="name" stroke="#778397"/><YAxis stroke="#778397"/><Tooltip contentStyle={{background:'#111823',border:'1px solid #263343'}}/><Bar dataKey="value" fill="#72ff9b"/></BarChart></ResponsiveContainer></div></div><div className="card"><div className="label">Like ratio</div><div className="value">{game.rating==null?'—':game.rating.toFixed(2)+'%'}</div><div className="row"><span className="muted">👍 Likes</span><b>{fmt(game.likes)}</b></div><div className="row"><span className="muted">👎 Dislikes</span><b>{fmt(game.dislikes)}</b></div></div></section>}
   {tab==='technical'&&<section className="grid">{[['Universe ID',game.id],['Root Place ID',game.placeId],['Max players',game.maxPlayers],['Price',game.price],['Private server price',game.privateServerPrice],['Avatar type',game.avatarType],['Creator',game.creator?.name],['Created',date(game.created)],['Updated',date(game.updated)]].map(([a,b])=><div className="card" key={String(a)}><div className="label">{a}</div><div className="value" style={{fontSize:17}}>{b??'—'}</div></div>)}</section>}
   {tab==='raw'&&<pre className="card" style={{overflow:'auto',whiteSpace:'pre-wrap',fontSize:12}}>{JSON.stringify(game.raw,null,2)}</pre>}
  </>}
 </main>
}